[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['test/=lib/ds-test/src/','oz/=lib/openzeppelin-contracts/contracts/', 'sm/=lib/solmate/src', 'std/=lib/forge-std/src/']

# See more config options https://github.com/gakonst/foundry/tree/master/config